name: iOS IPA Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
      
      - name: IPA olustur
        run: |
          mkdir -p $RUNNER_TEMP/ipa/Payload
          cp -r "$RUNNER_TEMP/App.xcarchive/Products/Applications/App.app" $RUNNER_TEMP/ipa/Payload/
          cd $RUNNER_TEMP/ipa
          zip -r App.ipa Payload/

      - name: IPA yukle
        uses: actions/upload-artifact@v4
        with:
          name: StokPanel-iOS
          path: ${{ runner.temp }}/ipa/App.ipa
          retention-days: 7
